config/routes.rb
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  devise_for :users
  resources :prompts do 
    resources :conversations, except: [:update, :edit, :index] do
      resources :messages, only: [:create]
    end 
  end 
  root "pages#home"
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  validates :body, :conversation_id, presence: :true
  validate :has_legal_creating_entity
  after_create_commit { broadcast_append_to self.conversation_id }
  scope :user_messages, -> { where(creating_entity: ENTITIES[0]) }
  scope :character_messages, -> { where(creating_entity: ENTITIES[1]) }
  scope :translator_messages, -> { where(creating_entity: ENTITIES[2]) }

  ENTITIES = ["user", "ai", "system"].freeze 

  private
  def has_legal_creating_entity
    if !ENTITIES.include?(creating_entity)
      errors.add(:creating_entity, "must be a valid entity in Message::ENTITIES") 
    end 
  end 
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_conversation
  before_action :set_prompt

  def create
    @new_message = Message.new
    @message = @conversation.messages.build(message_params)
    @message.creating_entity = "user"
    
    is_saved = @message.save
    render turbo_stream: [
      turbo_stream.replace('message_form', partial: "messages/message_form", locals: { message: @new_message }),
      # turbo_stream.replace('message_errors', partial: "message_errors", locals: { message: @message })
    ]

    if is_saved
      # Prompt conversation model for response?
      @conversation.create_responses
    end

  end

  private
    def set_conversation
      @conversation = Conversation.visible_by_user(current_or_guest_user).find(params[:conversation_id])
    end 

    def set_prompt
      @prompt = @conversation.prompt
    end 

    def message_params
      params.require(:message).permit(:body, :conversation_id)
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_message.html.erb
<div id="<%= dom_id message %>"> </div>

<div class="card my-1">
  <div class="card-body">
    <% if message.creating_entity == "user" %>
        <p class="card-text text-end fw-bold"> You </p>
        <p class="card-text text-end"> <%= message.body %> </p>
    <% elsif message.creating_entity == "ai"%>
        <p class="card-text fw-bold"> <%= message.conversation.prompt.ai_name %> </p>
        <p class="card-text"> <%= message.body %> </p>
    <% else %>
      <p class="card-text fw-bold"> Translator </p>
      <p class="card-text"> <%= message.body %> </p>
    <% end %>
  </div>
</div>

app/views/messages/_message_errors.html.erb
<div id="message_errors">
  <% if message.errors.any? %>
    <div class="alert alert-danger">

      <ul>
        <% message.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/messages/_message_form.html.erb
<div id="message_form">
  <%= form_with(model: message, url: prompt_conversation_messages_path(@prompt, @conversation), remote: true) do |form| %>
    <div id="message_errors"></div>

    <div class="form-group pt-3">
      <%= form.text_area :body, class: "form-control", placeholder: "Start Typing..." %>
    </div>

    <div class="form-group">
      <%= form.submit "Send", class: "btn btn-dark mt-1" %>
    </div>
  <% end %>
</div>