config/routes.rb
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  devise_for :users
  resources :prompts do 
    resources :conversations, except: [:update, :edit, :index] do
      resources :messages, only: [:create]
    end 
  end 
  root "pages#home"
end

app/models/prompt.rb
class Prompt < ApplicationRecord
  belongs_to :user
  has_many :conversations, dependent: :destroy
  validates :ai_name, :setting, :description, :user_id, presence: :true
  scope :visible_by_all, -> { where(visible_to_all: true) }
  scope :visible_by_user, ->(user) {
    where(user_id: user.id).or(where(visible_to_all: true))
  }
  
end

app/controllers/prompts_controller.rb
class PromptsController < ApplicationController
  include PromptsHelper
  before_action :set_prompt, only: %i[ show edit update destroy ]

  # GET /prompts or /prompts.json
  def index
    @prompts = Prompt.visible_by_user(current_or_guest_user)
    @prompt = Prompt.new
  end

  # GET /prompts/1 or /prompts/1.json
  def show
  end

  # GET /prompts/new
  def new
    if user_signed_in?
      @prompt = Prompt.new
    else
      redirect_to new_user_session_path, notice: "Please log in to create a prompt."
    end 
  end

  # GET /prompts/1/edit
  def edit
    if !user_can_modify(@prompt)
      redirect_to prompts_path
    end 
  end

  # POST /prompts or /prompts.json
  def create
    @prompt = Prompt.new(prompt_params)
    @prompt.user = current_or_guest_user

    
    if user_can_modify(@prompt) && @prompt.save
      redirect_to prompt_url(@prompt), notice: "Prompt was successfully created." 
    else 
      render :new, status: :unprocessable_entity
    end 
  end

  # PATCH/PUT /prompts/1 or /prompts/1.json
  def update
    if user_can_modify(@prompt) && @prompt.update(prompt_params)
      redirect_to prompt_url(@prompt), notice: "Prompt was successfully updated." 
    else 
      render :edit, status: :unprocessable_entity 
    end 
  end

  # DELETE /prompts/1 or /prompts/1.json
  def destroy
    if user_can_modify(@prompt)
      @prompt.destroy
      redirect_to prompts_url, notice: "Prompt deleted"
    else 
      redirect_to prompt_url(@prompt)
    end 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prompt
      if Prompt.visible_by_user(current_or_guest_user).exists? params[:id]
        @prompt = Prompt.visible_by_user(current_or_guest_user).find(params[:id])
      else 
        redirect_to prompts_url, notice: "That prompt does not exist"
      end 
    end

    # Only allow a list of trusted parameters through.
    def prompt_params
      params.require(:prompt).permit(:ai_name, :setting, :description, :visible_to_all)
    end
end

app/helpers/prompts_helper.rb
module PromptsHelper
    def user_can_modify(prompt)
        if prompt.visible_to_all && !current_or_guest_user.is_admin
            return false
        else 
            return true
        end 
      end 
end

app/views/prompts/_form.html.erb
<%= form_with(model: prompt, class: "form") do |form| %>

  <%= render 'prompt_errors', prompt: prompt %>

  <div class="mb-3">
    <%= form.label :ai_name, "Character Name", class: "form-label" %>
    <%= form.text_field :ai_name, class: "form-control" %>
  </div>
  <p> The character's name </p>

  <div class="mb-3">
    <%= form.label :setting, class: "form-label" %>
    <%= form.text_area :setting, class: "form-control" %>
  </div>
  <p> Tell the computer how to act, ex: "You are an aspiring musician about to step on stage talking to a longtime fan." More details results in a more interesting character. </p>

  <div class="mb-3">
    <%= form.label :description, class: "form-label" %>
    <%= form.text_area :description, class: "form-control" %>
  </div>
  <p> Give a human readable description, ex: "An aspiring musician talks to an eager fan." </p>

  <% if current_or_guest_user.is_admin %>
    <div class="mb-3 form-check">
      <%= form.check_box :visible_to_all, class: "form-check-input" %>
      <%= form.label :visible_to_all, class: "form-check-label" %>
      <p> ADMIN OPTION: MAKES THE PROMPT VISIBLE TO EVERYBODY" </p>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.submit "Submit", class: "btn btn-dark" %>
  </div>
<% end %>

app/views/prompts/_prompt.html.erb
<div class="col-sm-6 col-lg-4 px-2">
  <div class="card m-2 bg-light">
    <div class="card-body">
      <h5 class="card-title"> <%= prompt.ai_name %> </h5>
      <p class="card-text"> <%= prompt.description %> </p>
        <% if current_or_guest_user.is_admin%>
          <p>
            <strong>visible_to_all:</strong>
            <%= prompt.visible_to_all %>
          </p>
        <%end%>

      <%= link_to "Show prompt", prompt, class: "btn btn-outline-secondary mx-1" %>

      <% if !prompt.visible_to_all || current_or_guest_user.is_admin %>
          <%= link_to "Edit prompt", edit_prompt_path(prompt), class: "btn btn-outline-secondary mx-1" %>
      <% end %>


      <%= link_to "Start conversation", new_prompt_conversation_path(prompt), class: "btn btn-outline-secondary mx-1" %>
    </div>
  </div>
</div>

app/views/prompts/_prompt_errors.html.erb
<% if prompt.errors.any? %>
  <div class="alert alert-danger">
    <ul class="mb-0">
      <% prompt.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/prompts/edit.html.erb
<%= render 'navbar' %>

<div class="backgroundContainer">

  <div class="container d-flex justify-content-center align-items-center">
    <div class="jumbotron formJumbotron">
      <h1 class="display-4">New Prompt</h1>

      <%= render "form", prompt: @prompt %>
      <p> Note: Submiting changes will terminate all associated conversations </p>
      <hr class="my-4">
      <%= link_to "Back to Prompts", prompts_path, class: "btn btn-outline-dark mx-1" %>
      <div class="btn-group">
        <%= button_to "Delete Prompt", prompt_path(@prompt), method: :delete, class: "btn btn-outline-danger" %>
      </div>
    </div>
  </div>


</div>

app/views/prompts/index.html.erb
<%= render 'navbar' %>

<div class="backgroundContainer promptsBackground px-xl-5 pb-5">
    <div class="row py-5">
        <div class="px-0 col-md-10 col-lg-8 col-xl-6">
            <div class="jumbotron mx-4 mx-sm-5 promptsJumbotron">
                <h5 class="display-5"> Prompts </h5>
                <hr class="my-4">
                  <p> Click "Start conversation" on a prompt to begin, or add prompt to create a new one. </p>

                  <%= link_to new_prompt_path, class: "btn btn-lg btn-outline-dark m-2" do %>
                    <i class="fa-solid fa-circle-plus" style="color: #000000;"></i> Add Prompt
                  <% end %>

            </div>
        </div>
    </div>

  <div class="row g-0 px-2" id="prompts">
    <% @prompts.each do |prompt| %>
      <%= render prompt %>
    <% end %>
  </div>

</div>

app/views/prompts/new.html.erb
<%= render 'navbar' %>

<div class="backgroundContainer">

  <div class="container d-flex justify-content-center align-items-center">
    <div class="jumbotron formJumbotron">
      <h1 class="display-4">New Prompt</h1>

      <%= render "form", prompt: @prompt %>

      <hr class="my-4">

      <%= link_to "Back to Prompts", prompts_path, class: "btn btn-outline-dark" %>
    </div>
  </div>


</div>

app/views/prompts/show.html.erb
<%= render 'navbar' %>

<div class="backgroundContainer">

  <div class="container d-flex justify-content-center align-items-center">
    <div class="jumbotron formJumbotron">
      <h1 class="display-4"> <%= @prompt.ai_name %> </h1>

          <p>
            <strong> Setting:</strong>
            <%= @prompt.setting %>
          </p>

          <p>
            <strong> Description: </strong>
            <%= @prompt.description %>
          </p>

          <p>
            <strong> Visible To: </strong>
            <% if @prompt.visible_to_all %>
            Everyone
            <% else%>
            Just You
            <%end %>
          </p>
      
      <hr class="my-4">

    <%= link_to "Start conversation", new_prompt_conversation_path(@prompt), class: "btn btn-outline-dark mx-1" %>
    <%= link_to "Back to Prompts", prompts_path, class: "btn btn-outline-dark mx-1" %>

    <% if !@prompt.visible_to_all || current_or_guest_user.is_admin %>
      <div class="btn-group">
        <%= button_to "Delete Prompt", prompt_path(@prompt), method: :delete, class: "btn btn-outline-danger" %>
      </div>
    <% end %>

    </div>
  </div>


</div>