config/routes.rb
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  devise_for :users
  resources :prompts do 
    resources :conversations, except: [:update, :edit, :index] do
      resources :messages, only: [:create]
    end 
  end 
  root "pages#home"
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  include ConversationsHelper
  belongs_to :prompt
  belongs_to :user
  has_many :messages, dependent: :destroy
  validates :training_language, :native_language, :prompt_id, :user_id, presence: :true
  scope :visible_by_user, ->(user) {
    where(user_id: user.id)
  }


  def create_responses 
    character_respond
    translator_respond
  end 

  private
    def character_respond
      client = OpenAI::Client.new
      dialouge = [{role: 'system', content: "You are playing the character in the following setting: " + prompt.setting + 
                  ".  Your name is " + prompt.ai_name + ". Respond to the user's inputs only in the following language: " + training_language + ".  Do not break character."}]

      self.messages.each do |m|
        if m.creating_entity == Message::ENTITIES[0]
          dialouge.push({ role: Message::ENTITIES[0], content: m.body})
        elsif m.creating_entity == Message::ENTITIES[1]
          dialouge.push({ role: 'assistant', content: m.body})
        end 
      end 

      message_body = client.chat(
      parameters: {
            model: MODEL,
            messages: dialouge,
            temperature: TEMPERATURE
      }).dig('choices', 0, 'message', 'content' )

      self.messages.create(creating_entity: Message::ENTITIES[1], body: message_body)
    end

    def translator_respond
      client = OpenAI::Client.new
      dialouge = [
                      {role: 'system', content: "You will be given a snippet of text in the following language: " + training_language + 
                      ".  If the message has grammar errors, respond with the corrected message.  If the message is already correct, respond with 'no problems' in" + native_language + ". If the text makes very little sense, respond with 'error' in " + native_language + "."},
                      {role: 'user', content: messages[-2].body}
                    ]

        

      message_body = client.chat(
        parameters: {
              model: MODEL,
              messages: dialouge,
              temperature: 0
      }).dig('choices', 0, 'message', 'content' )  

      self.messages.create(creating_entity: Message::ENTITIES[2], body: message_body)
    end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :set_prompt
  before_action :set_conversation, only: %i[show destroy]

  # GET /conversations/1 or /conversations/1.json
  def show
    @messages = @conversation.messages
    @new_message = Message.new
  end

  # GET /conversations/new
  def new
    @conversation = Conversation.new
  end

  # POST /conversations or /conversations.json
  def create
    @conversation = @prompt.conversations.build(conversation_params)
    @conversation.user = current_or_guest_user

    @conversation.native_language="English" # Native language not yet supported

    if @conversation.save
      redirect_to prompt_conversation_url(@prompt, @conversation), notice: "Conversation was successfully created."
    else
      render :new, status: :unprocessable_entity 
    end 
  end

  # DELETE /conversations/1 or /conversations/1.json
  def destroy
    @conversation.destroy
    redirect_to prompts_url, notice: "Conversation ended."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_conversation
      if Conversation.visible_by_user(current_or_guest_user).exists?(params[:id])
        @conversation = Conversation.visible_by_user(current_or_guest_user).find(params[:id])
      else
        redirect_to prompts_url, notice: "That conversation does not exist."
      end
    end

    def set_prompt
      if Prompt.visible_by_user(current_or_guest_user).exists? params[:prompt_id]
        @prompt = Prompt.visible_by_user(current_or_guest_user).find(params[:prompt_id])
      else 
        redirect_to prompts_url, notice: "That prompt does not exist"
      end 
    end

    # Only allow a list of trusted parameters through.
    def conversation_params
      params.require(:conversation).permit(:training_language, :native_language, :prompt_id)
    end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
    LANGUAGES = [
        '普通话',         # Mandarin Chinese
        'español',        # Spanish
        'English',        # English
        'हिन्दी',         # Hindi
        'বাংলা',          # Bengali
        'português',      # Portuguese
        'русский',        # Russian
        '日本語',          # Japanese
        'پنجابی',         # Western Punjabi
        'मराठी',         # Marathi
        'తెలుగు',        # Telugu
        '吴语',            # Wu Chinese
        'Türkçe',         # Turkish
        '한국어',           # Korean
        'français',       # French
        'Deutsch',        # German
        'Tiếng Việt',     # Vietnamese
        'தமிழ்',         # Tamil
        '粤语',           # Yue Chinese (Cantonese)
        'اردو',          # Urdu
        'basa Jawa',      # Javanese
        'italiano',       # Italian
        'لغة مصرية عامية', # Egyptian Arabic
        'ગુજરાતી',       # Gujarati
        'فارسی',         # Iranian Persian
        'भोजपुरी',       # Bhojpuri
        'Bân-lâm-gú',    # Min Nan Chinese
        '客家語/Hak-kâ-ngî', # Hakka Chinese
        '晋语',           # Jin Chinese
        'Hausa'          # Hausa
    ].freeze

    MODEL = "gpt-3.5-turbo"
    TEMPERATURE = 1.0
end

app/views/conversations/_conversation.html.erb
<div id="conversation">
  <p>
  <strong> Prompt: </strong>
    <%= conversation.prompt.description %>
  </p>

    <p>
  <strong> Character Name:</strong>
    <%= conversation.prompt.ai_name %>
  </p>

  <p>
  <strong>Training language:</strong>
    <%= conversation.training_language %>
  </p>

  <div id="messages">
    <h4> Messages </h4>
    <%= render @messages %>
  </div>

</div>

app/views/conversations/_conversation_form.html.erb
<%= form_with(model: conversation, url: prompt_conversations_path) do |form| %>
  <% if conversation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(conversation.errors.count, "error") %> prohibited this conversation from being saved:</h2>

      <ul>
        <% conversation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :training_language, style: "display: block" %>
    <%= form.select :training_language, Conversation::LANGUAGES%>
  </div>

<div class="my-3">
  <%= form.submit "Submit", class: "btn btn-dark" %>
</div>
<% end %>

app/views/conversations/_form.html.erb
<%= form_with(model: conversation, url: prompt_conversations_path) do |form| %>
  <% if conversation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(conversation.errors.count, "error") %> prohibited this conversation from being saved:</h2>

      <ul>
        <% conversation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :training_language, style: "display: block" %>
    <%= form.select :training_language, Conversation::LANGUAGES%>
  </div>

  <div>
    <%= form.label :native_language, style: "display: block" %>
    <%= form.select :native_language, Conversation::LANGUAGES%>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/conversations/new.html.erb
<%= render 'navbar' %>

<div class="backgroundContainer">

  <div class="container d-flex justify-content-center align-items-center">
    <div class="jumbotron formJumbotron">
      <h1 class="display-4">New Conversation </h1>

      <%= render "conversation_form", conversation: @conversation %>

      <hr class="my-4">

      <%= link_to "Back to Prompts", prompts_path, class: "btn btn-outline-dark" %>
    </div>
  </div>


</div>

app/views/conversations/show.html.erb
<%= render 'navbar' %>
<%= turbo_stream_from @conversation.id %>

<div class="backgroundContainer">

  <div class="d-flex justify-content-center py-5 conversationContainer">
    <div class="jumbotron conversationJumbotron py-5 px-3 px-sm-5">
        <%= render @conversation %>

        <div>
            <%= render "messages/message_form", message: @new_message %>

          <%= button_to "End conversation", prompt_conversation_path(@prompt, @conversation), method: :delete, class: "btn btn-outline-dark mt-1" %>
        </div>

    </div>
  </div>


</div>